In [5]:
# Quadratic Form 

X = np.array([1,2,3])

A = np.arange(1,10).reshape(3,3)

X.T @ A @ X

# practice

print(X.T @ A @ X)

print(1/2 * (X.T @ A @ X + X.T @ A.T @ X))

228
228.0


In [30]:
# submatrix

In [29]:
# matrix norm 

import math

A = (np.arange(9)-4).reshape((3,3))
A

np.linalg.norm(A)

v1 = (np.arange(4)-3).reshape((4,1))
v_norm = np.linalg.norm(v1)

print(v_square)
print(v_norm * v_norm)

[[14]]
14.0


In [31]:
# positive definite
# positive semi-definite

In [44]:
# trace

np.trace(np.eye(4))

A = (np.arange(4)-3).reshape((2,2))
X = (np.arange(2)-3).reshape(2,1)

# practice
print(np.trace(X.T @ A @ X))
print(np.trace(A @ X @ X.T))
print(np.trace(X @ X.T @ A))



-45
-45
-45


In [47]:
# determinant
A = np.array([[1,2,3],[4,5,6], [7,8,9]])

np.linalg.det(A)

-9.51619735392994e-16

In [48]:
# system of linear equations

In [52]:
# inverse matrix
# invertible matrix or singular matrix
# new concept: matrix of cofators or cofactor matrix, comatrix
# new concept: adjoint matrix, adjugate matrix

# practice
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
np.linalg.inv(A)

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [72]:
# inverse matrix @ solution of linear equation

import math

A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A_inv = np.linalg.inv(A)

B = np.array([[1],[2],[3]])

solution = A_inv @ B
solution

x, resid, rank, s = np.linalg.lstsq(A,B)

x


array([[1.00000000e+00],
       [6.45571345e-16],
       [2.00000000e+00]])

In [114]:
# system of linear equation & linear prediction model

# practice
from sklearn.datasets import load_boston

boston = load_boston()

X = boston.data
y = boston.target 

A = boston.data[:4, [0,4,5,6]] # 범죄율, 공기 오염도, 방 개수, 오래된 정도 

b = y[:4]

w1 = np.linalg.inv(A) @ b
w2 = np.linalg.lstsq(A,b)[0]

print(w1)
print(w2)


[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]
[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


-413.51759840148617

In [135]:
# number of knowns(N) & number of equations(M)
# case: N = M / N < M / N > M
# if N < M then solution could not exist.
# but can solve this problem with least square problem

A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
b = np.array([[2],[2],[3],[4.1]])

# pseudo_inv of A
A_pseudo_inv = np.linalg.inv(A.T @ A) @ A.T

x1 = A_pseudo_inv @ b

A @ x1 # 거의 b와 같다. 오차가 매우 작다. 

x2, resid, rank, s = np.linalg.lstsq(A,b)

print(x1)
print(x2)

# resid
print(resid, np.linalg.norm(A @ x1 -b) **2)


[[1.03333333]
 [0.95      ]
 [1.05      ]]
[[1.03333333]
 [0.95      ]
 [1.05      ]]
[0.00166667] 0.0016666666666666698
[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


In [152]:
# practice 
from sklearn.datasets import load_boston

boston = load_boston()

X = boston.data
y = boston.target

X_pinv = np.linalg.inv(X.T @ X) @ X.T

w = X_pinv @ y

sum(w) # why is s not 1?


13.775986264171552