In [1]:
# broadcasting 

from sklearn.datasets import load_iris

iris = load_iris()

x1 = iris.data[0,:]

v1 = np.array([x1])

print(v1 - 2*np.ones((4,1)))

# mean-removed vector 

x = 0
v1_mean = 0

for i in x1:
    x += i 
    v1_mean = x / len(x1)

print(v1 - v1_mean)

[[ 3.1  1.5 -0.6 -1.8]
 [ 3.1  1.5 -0.6 -1.8]
 [ 3.1  1.5 -0.6 -1.8]
 [ 3.1  1.5 -0.6 -1.8]]
[[ 2.55  0.95 -1.15 -2.35]]
