In [20]:
# transpose matrix

from sklearn.datasets import load_iris

iris = load_iris()

x1 = iris.data[0,:]
x2 = iris.data[1,:]

X = np.array([x1, x2])
X.T # T is attribute, not method so should not call this with ()

x1.T # Can't transpose 1-dimension matrix

print(X)
print(X.T)
print(X.T.T)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[[5.1 4.9]
 [3.5 3. ]
 [1.4 1.4]
 [0.2 0.2]]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
