In [5]:
# zeros-vector

np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [7]:
# ones-vector

np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [10]:
# square matrix

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# diagonal matrix

np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
# identity matrix

print(np.identity(3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# symmetric matrix
# only square matrix

x1 = [1,2,3]
x2 = [2,1,4]
x3 = [3,4,1]

np.array([x1,x2,x3])

array([[1, 2, 3],
       [2, 1, 4],
       [3, 4, 1]])