In [11]:
# plus & minus vector * matrix

from sklearn.datasets import load_iris

iris = load_iris()

x1 = iris.data[0,:]
x2 = iris.data[1,:]

v1 = np.array([x1])
v2 = np.array([x2])

print(v1 + v2)
print(v1 - v2)

x3 = iris.data[2,:]
x4 = iris.data[3,:]
x5 = iris.data[4,:]
x6 = iris.data[5,:]

m1 = np.array([x3, x4])
m2 = np.array([x5, x6])

print(m1 + m2)
print(m1 - m2)


[[10.   6.5  2.8  0.4]]
[[0.2 0.5 0.  0. ]]
[[ 9.7  6.8  2.7  0.4]
 [10.   7.   3.2  0.6]]
[[-0.3 -0.4 -0.1  0. ]
 [-0.8 -0.8 -0.2 -0.2]]
