In [3]:
# sum of squares
# for variance or standard deviation

from sklearn.datasets import load_iris

iris = load_iris()

x1 = iris.data[0,:]

x1.T @ x1 


40.26

In [23]:
# matrix * matrix

from sklearn.datasets import load_iris

iris = load_iris()

x0 = iris.data[0,:]
x1 = iris.data[1,:]
x2 = iris.data[2,:]
x3 = iris.data[3,:]
x4 = iris.data[4,:]

m1 = np.array([x0,x1])
m2 = np.array([x2, x3, x4])

# 2x4 * 4x3 = 2x3
print(m1 @ m2.T)
print(np.dot(m1,m2.T))

[[37.03 36.45 40.1 ]
 [34.49 33.98 37.3 ]]
[[37.03 36.45 40.1 ]
 [34.49 33.98 37.3 ]]


In [33]:
# law of commutative of matrix
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,8],[7,6]])

# this law is not established
print(a @ b)
print(b @ a)

# law of distribution - established
print(a @ (b + c))
print(a @ b + a @ c)

# these law in transpose operation
print((a + b).T)
print(a.T + b.T)

print((a @ b).T)
print(b.T @ a.T)


[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[42 42]
 [98 98]]
[[42 42]
 [98 98]]
[[ 6 10]
 [ 8 12]]
[[ 6 10]
 [ 8 12]]
[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [47]:
# practice 
from sklearn.datasets import load_iris

iris = load_iris().data
N = iris.shape[0]

ones = np.ones(N).reshape(N,1)

iris_bar = (ones @ ones.T) @ iris / N 

iris_bar

array([[5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333, 3.758     , 1.19933333],
       [5.84333333, 3.05733333,