In [1]:
# multiply scalar & vector/matrix

from sklearn.datasets import load_iris

iris = load_iris()

x1 = iris.data[0,:]

v1 = np.array([x1])

print(2*v1)
print(3*v1)

x2 = iris.data[1,:]
x3 = iris.data[2,:]

m1 = np.array([x2, x3])

print(2*m1)
print(3*m1)

[[10.2  7.   2.8  0.4]]
[[15.3 10.5  4.2  0.6]]
[[9.8 6.  2.8 0.4]
 [9.4 6.4 2.6 0.4]]
[[14.7  9.   4.2  0.6]
 [14.1  9.6  3.9  0.6]]
